FROM quay.io/keycloak/keycloak:25.0.0
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KC_DB=postgres
ENV KC_DB_URL=${DATABASE_URL}
ENV KC_DB_USERNAME=${DB_USERNAME}
ENV KC_DB_PASSWORD=${DB_PASSWORD}
EXPOSE 8080
ENTRYPOINT ["kc.sh", "start-dev"]
